//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spa_Personas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrador
    {
        public int Id { get; set; }
        public string Documento_Administrador { get; set; }
        public string userName { get; set; }
        public string Clave { get; set; }
    }
}
