//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spa_Personas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_factura
    {
        public int Id { get; set; }
        public int CantidadProducto { get; set; }
        public int CantidadServicio { get; set; }
        public int IdProducto { get; set; }
        public int IdFactura { get; set; }
        public int IdServicio { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}
