//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spa_Personas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        public int Id { get; set; }
        public int Stock { get; set; }
        public System.DateTime UltimoRestock { get; set; }
        public int IdProducto { get; set; }
        public int IdSede { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Sede Sede { get; set; }
    }
}
