//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spa_Personas.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor_Producto
    {
        public int Id { get; set; }
        public Nullable<int> Id_Proveedor { get; set; }
        public Nullable<int> Id_Producto { get; set; }

        [JsonIgnore]
        public virtual Producto Producto { get; set; }
        [JsonIgnore]
        public virtual Proveedor Proveedor { get; set; }
    }
}
