//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spa_Personas.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio_Sede
    {
        public int Id { get; set; }
        public int IdServicio { get; set; }
        public int IdSede { get; set; }

        [JsonIgnore]
        public virtual Sede Sede { get; set; }
        [JsonIgnore]
        public virtual Servicio Servicio { get; set; }
    }
}
